### ISSUE TITLE
你的登入密码和用域名是什么？

### ISSUE THREAD

**Issue by Tompythonorange** [chenkai0520/cesium-demos#3]
进入你的在线项目的之后有几个功能需要登入哇。用户名和密码是什么？谢谢。

**Comment by ckvv** [comment]
> 进入你的在线项目的之后有几个功能需要登入哇。用户名和密码是什么？谢谢。

在线项目只是把页面托管到github上了，想完整使用的话可以配[GraduationServer](https://github.com/chenkai0520/GraduationServer)使用
